#ifndef RMDIRCOMMANDGLOBAL_H
#define RMDIRCOMMANDGLOBAL_H

#ifdef RMDIRCOMMAND_MAKER
    #define RMDIRCOMMAND_API Q_DECL_EXPORT
#else
    #define RMDIRCOMMAND_API Q_DECL_IMPORT
#endif

#endif // RMDIRCOMMANDGLOBAL_H
