#ifndef TASKLISTCOMMANDGLOBAL_H
#define TASKLISTCOMMANDGLOBAL_H

#ifdef TASKLISTCOMMAND_MAKER
    #define TASKLISTCOMMAND_API Q_DECL_EXPORT
#else
    #define TASKLISTCOMMAND_API Q_DECL_IMPORT
#endif

#endif // TASKLISTCOMMANDGLOBAL_H
