#ifndef TRACERTCOMMANDGLOBAL_H
#define TRACERTCOMMANDGLOBAL_H

#ifdef TRACERTCOMMAND_MAKER
    #define TRACERTCOMMAND_API Q_DECL_EXPORT
#else
    #define TRACERTCOMMAND_API Q_DECL_IMPORT
#endif

#endif // TRACERTCOMMANDGLOBAL_H
