#ifndef DIRCOMMANDGLOBAL_H
#define DIRCOMMANDGLOBAL_H

#ifdef DIRCOMMAND_MAKER
    #define DIRCOMMAND_API Q_DECL_EXPORT
#else
    #define DIRCOMMAND_API Q_DECL_IMPORT
#endif

#endif // DIRCOMMANDGLOBAL_H
