#ifndef MKDIRCOMMANDGLOBAL_H
#define MKDIRCOMMANDGLOBAL_H

#ifdef MKDIRCOMMAND_MAKER
    #define MKDIRCOMMAND_API Q_DECL_EXPORT
#else
    #define MKDIRCOMMAND_API Q_DECL_IMPORT
#endif

#endif // MKDIRCOMMANDGLOBAL_H
