#ifndef TASKKILLCOMMANDGLOBAL_H
#define TASKKILLCOMMANDGLOBAL_H

#ifdef TASKKILLCOMMAND_MAKER
    #define TASKKILLCOMMAND_API Q_DECL_EXPORT
#else
    #define TASKKILLCOMMAND_API Q_DECL_IMPORT
#endif

#endif // TASKKILLCOMMANDGLOBAL_H
