#ifndef IPCONFIGCOMMANDGLOBAL_H
#define IPCONFIGCOMMANDGLOBAL_H

#ifdef IPCONFIGCOMMAND_MAKER
    #define IPCONFIGCOMMAND_API Q_DECL_EXPORT
#else
    #define IPCONFIGCOMMAND_API Q_DECL_IMPORT
#endif

#endif // IPCONFIGCOMMANDGLOBAL_H
