#ifndef LAUNCHERCOMMANDGLOBAL_H
#define LAUNCHERCOMMANDGLOBAL_H

#ifdef LAUNCHERCOMMAND_MAKER
    #define LAUNCHERCOMMAND_API Q_DECL_EXPORT
#else
    #define LAUNCHERCOMMAND_API Q_DECL_IMPORT
#endif

#endif // LAUNCHERCOMMANDGLOBAL_H
