#ifndef PINGCOMMANDGLOBAL_H
#define PINGCOMMANDGLOBAL_H

#ifdef PINGCOMMAND_MAKER
    #define PINGCOMMAND_API Q_DECL_EXPORT
#else
    #define PINGCOMMAND_API Q_DECL_IMPORT
#endif

#endif // PINGCOMMANDGLOBAL_H
