#ifndef WINSYSTEMTOOLCOMMANDGLOBAL_H
#define WINSYSTEMTOOLCOMMANDGLOBAL_H

#ifdef WINSYSTEMTOOLCOMMAND_MAKER
    #define WINSYSTEMTOOLCOMMAND_API Q_DECL_EXPORT
#else
    #define WINSYSTEMTOOLCOMMAND_API Q_DECL_IMPORT
#endif

#endif // WINSYSTEMTOOLCOMMANDGLOBAL_H
